export const AuthAction = {
  SET_PAGE_HEADER: "SET_PAGE_HEADER",
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  CLEAR_ERROR: "CLEAR_ERROR",
  LOGOUT: "LOGOUT",
  FETCH_USER_PROFILE_SUCCESS: "FETCH_USER_PROFILE_SUCCESS",
  FETCH_USER_PROFILE_FAILURE: "FETCH_USER_PROFILE_FAILURE",
  FETCH_QUOTE_SUCCESS: "FETCH_QUOTE_SUCCESS",
  FETCH_QUOTE_FAILURE: "FETCH_QUOTE_FAILURE",
  SET_ONLINE_STATUS: "SET_ONLINE_STATUS",
};
