export const ManagementAction = {
  FETCH_TRANSACTION_TYPE: "FETCH_TRANSACTION_TYPE",
  REGISTER_TRANSACTION_TYPE: "REGISTER_TRANSACTION_TYPE",
  CHANGE_TRANSACTION_TYPE_NAME: "CHANGE_TRANSACTION_TYPE_NAME",
  CHANGE_TRANSACTION_TYPE_DESCRIPTION: "CHANGE_TRANSACTION_TYPE_DESCRIPTION",
  CLEAR_TRANSACTION_TYPE: "CLEAR_TRANSACTION_TYPE",

  FETCH_CATEGORY: "FETCH_CATEGORY",
  REGISTER_CATEGORY: "REGISTER_CATEGORY",
  CHANGE_CATEGORY_NAME: "CHANGE_CATEGORY_NAME",
  CHANGE_CATEGORY_TYPE: "CHANGE_CATEGORY_TYPE",
  CHANGE_CATEGORY_DESCRIPTION: "CHANGE_CATEGORY_DESCRIPTION",
  CLEAR_CATEGORY: "CLEAR_CATEGORY",

  FETCH_BILL: "FETCH_BILL",
  REGISTER_BILL: "REGISTER_BILL",
};
