export const homeAction = {
  STATE_HOME_DATA: "STATE_HOME_DATA",
  FETCH_HOME_DATA: "FETCH_HOME_DATA",
  STATE_EXPENSE_BREAKDOWN: "STATE_EXPENSE_BREAKDOWN",
  FETCH_EXPENSE_BREAKDOWN: "FETCH_EXPENSE_BREAKDOWN",

  SET_TRANSACTION_TYPE_TITLE: "SET_TRANSACTION_TYPE_TITLE",
  CHANGE_TRANSACTION_TYPE_TITLE: "CHANGE_TRANSACTION_TYPE_TITLE",
};
