export const transactionAction = {
  GET_TRANSACTIONS: "GET_TRANSACTIONS",
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  CHANGE_DATE: "CHANGE_DATE",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  REGISTER_TRANSACTION_IN_ACTION: "REGISTER_TRANSACTION_IN_ACTION",
  CHANGE_STATE_MODAL_DELETE: "CHANGE_STATE_MODAL_DELETE",
  CLEAR_TRANSACTION_DATA: "CLEAR_TRANSACTION_DATA",
  CHANGE_TRANSACTION_DATA_DATE: "CHANGE_TRANSACTION_DATA_DATE",
  CHANGE_TRANSACTION_DATA_CATEGORY: "CHANGE_TRANSACTION_DATA_CATEGORY",
  CHANGE_TRANSACTION_DATA_AMOUNT: "CHANGE_TRANSACTION_DATA_AMOUNT",
  CHANGE_TRANSACTION_DATA_DESCRIPTION: "CHANGE_TRANSACTION_DATA_DESCRIPTION",
};
