export const transactionAction = {
  GET_TRANSACTIONS: "GET_TRANSACTIONS",
  SET_TRANSACTIONS: "SET_TRANSACTIONS",
  CHANGE_DATE: "CHANGE_DATE",
  CHANGE_CATEGORY: "CHANGE_CATEGORY",
  REGISTER_TRANSACTION_IN_ACTION: "REGISTER_TRANSACTION_IN_ACTION",
  CHANGE_STATE_MODAL_DELETE: "CHANGE_STATE_MODAL_DELETE",
};
