const FETCH_TRANSACTION_TYPE_SUCCESS = "FETCH_TRANSACTION_TYPE_SUCCESS";
const FETCH_TRANSACTION_TYPE_FAILURE = "FETCH_TRANSACTION_TYPE_FAILURE";
const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";
const MIGRATE_TRANSACTION_TYPE_TREE = "MIGRATE_TRANSACTION_TYPE_TREE";

export const CommonAction = {
  FETCH_TRANSACTION_TYPE_SUCCESS,
  FETCH_TRANSACTION_TYPE_FAILURE,
  FETCH_CATEGORY_SUCCESS,
  FETCH_CATEGORY_FAILURE,
  MIGRATE_TRANSACTION_TYPE_TREE,
};
