const FETCH_TRANSACTION_TYPE_SUCCESS = "FETCH_TRANSACTION_TYPE_SUCCESS";
const FETCH_TRANSACTION_TYPE_FAILURE = "FETCH_TRANSACTION_TYPE_FAILURE";
const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
const FETCH_CATEGORY_FAILURE = "FETCH_CATEGORY_FAILURE";
const MIGRATE_TRANSACTION_TYPE_TREE = "MIGRATE_TRANSACTION_TYPE_TREE";

const CLEAR_TRANSACTION_DATA = "CLEAR_TRANSACTION_DATA";
const CHANGE_TRANSACTION_DATA_DATE = "CHANGE_TRANSACTION_DATA_DATE";
const CHANGE_TRANSACTION_DATA_CATEGORY = "CHANGE_TRANSACTION_DATA_CATEGORY";
const CHANGE_TRANSACTION_DATA_AMOUNT = "CHANGE_TRANSACTION_DATA_AMOUNT";
const CHANGE_TRANSACTION_DATA_DESCRIPTION =
  "CHANGE_TRANSACTION_DATA_DESCRIPTION";

export const CommonAction = {
  FETCH_TRANSACTION_TYPE_SUCCESS,
  FETCH_TRANSACTION_TYPE_FAILURE,
  FETCH_CATEGORY_SUCCESS,
  FETCH_CATEGORY_FAILURE,
  MIGRATE_TRANSACTION_TYPE_TREE,
  CLEAR_TRANSACTION_DATA,
  CHANGE_TRANSACTION_DATA_DATE,
  CHANGE_TRANSACTION_DATA_CATEGORY,
  CHANGE_TRANSACTION_DATA_AMOUNT,
  CHANGE_TRANSACTION_DATA_DESCRIPTION,
};
